# Generated by Django 4.2.1 on 2023-06-08 15:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=120)),
                ('budget', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expense_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('user_total_expenses', models.PositiveBigIntegerField(default=0)),
                ('date_of_expense', models.DateTimeField(default=django.utils.timezone.now)),
                ('currency', models.CharField(choices=[('USD', 'U$S'), ('UYU', 'U$')], max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('category_of_expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
